# Generated by Django 6.0.5 on 2026-05-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
