# Generated by Django 6.0.5 on 2026-05-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_assigned_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='final_ai_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='final_ai_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_ai_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_ai_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='text_ai_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='text_ai_confidence',
            field=models.FloatField(default=0),
        ),
    ]
