# Generated by Django 6.0.5 on 2026-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_ai_reasoning_complaint_final_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
