# Generated by Django 6.0.5 on 2026-05-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_level', models.IntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='complaints.complaint')),
            ],
        ),
    ]
