# Generated by Django 6.0.5 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaintsla'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
