# Generated by Django 6.0.5 on 2026-05-12 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='civichotspot',
            name='days_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civichotspot',
            name='first_detected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civichotspot',
            name='last_detected_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
