# Generated by Django 6.0.5 on 2026-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_civichotspot_days_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civichotspot',
            name='growth_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='civichotspot',
            name='last_complaint_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civichotspot',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civichotspot',
            name='times_reactivated',
            field=models.IntegerField(default=0),
        ),
    ]
